# Generated by Django 6.0 on 2025-12-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('lauch_date', models.DateField()),
                ('artists', models.ManyToManyField(related_name='albums', to='artists.artist')),
                ('genres', models.ManyToManyField(related_name='albums', to='genres.genre')),
            ],
        ),
    ]
