# Generated by Django 6.0 on 2025-12-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='lauch_date',
            new_name='launch_date',
        ),
    ]
