# Generated by Django 6.0 on 2025-12-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(choices=[('USA', 'Estados Unidos'), ('BRAZIL', 'Brasil'), ('CAN', 'Canada'), ('ENG', 'England')], default='USA', max_length=20)),
            ],
        ),
    ]
